import { Montserrat } from "next/font/google";
import "../styles/theme.scss";
import { Header } from "@/components/common/Header";
import { Footer } from "@/components/common/Footer";
import ScrollToTop from "@/components/common/ScrollToTop";
import BrandPartnersWrapper from "@/components/home/BrandPartnersWrapper";
import ReduxProvider from "@/components/providers/ReduxProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Fiama Floral Shop NextJS",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
